//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balashova_PR8_Sport_.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID { get; set; }
        public string naimenov { get; set; }
        public int kolichestvo { get; set; }
        public decimal cena { get; set; }
        public int StranaID { get; set; }
    
        public virtual Strana Strana { get; set; }
    }
}
